# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates

import json
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from byteff2.toolkit.openmmtool import AmoebaCalculator


class DimerEnergyScannerFromParams:
    """
    从 params 文件夹读取已有文件进行二聚体能量扫描
    文件结构: ./params/{mol_name}/ 包含 .itp, .atp, .gro, _params.json 等文件
    """
    
    def __init__(self, params_dir='./params', work_dir='./dimer_scan_results'):
        """
        初始化扫描器
        
        Args:
            params_dir: 参数文件夹根目录
            work_dir: 工作目录，保存结果文件
        """
        self.params_dir = Path(params_dir)
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(exist_ok=True, parents=True)
        
        if not self.params_dir.exists():
            raise ValueError(f"参数目录不存在: {self.params_dir}")
    
    def find_molecule_files(self, mol_name: str):
        """
        查找分子的所有必需文件
        
        Args:
            mol_name: 分子名称
            
        Returns:
            files: 包含所有文件路径的字典
        """
        mol_dir = self.params_dir / mol_name
        
        if not mol_dir.exists():
            raise ValueError(f"分子目录不存在: {mol_dir}")
        
        # 查找文件
        files = {}
        
        # 查找 .itp 文件
        itp_files = list(mol_dir.glob(f'{mol_name}.itp'))
        if not itp_files:
            raise ValueError(f"未找到 {mol_name}.itp 文件")
        files['itp'] = str(itp_files[0])
        
        # 查找 .atp 文件（atomtypes 定义）
        atp_files = list(mol_dir.glob(f'{mol_name}.atp'))
        if atp_files:
            files['atp'] = str(atp_files[0])
        else:
            files['atp'] = None
            print(f"  警告: 未找到 {mol_name}.atp 文件")
        
        # 查找 .gro 文件
        gro_files = list(mol_dir.glob(f'{mol_name}.gro'))
        if not gro_files:
            raise ValueError(f"未找到 {mol_name}.gro 文件")
        files['gro'] = str(gro_files[0])
        
        # 查找参数 JSON 文件
        params_files = list(mol_dir.glob(f'{mol_name}.json'))
        if not params_files:
            raise ValueError(f"未找到 {mol_name}.json 文件")
        files['params'] = str(params_files[0])
        
        # 查找元数据文件（可选）
        metadata_files = list(mol_dir.glob(f'{mol_name}_nb_params.json'))
        if metadata_files:
            files['metadata'] = str(metadata_files[0])
        else:
            files['metadata'] = None
        
        print(f"找到 {mol_name} 的文件:")
        for key, path in files.items():
            if path:
                print(f"  {key}: {path}")
        
        return files
    
    def create_dimer_topology(self, mol1_name: str, mol2_name: str,
                             files1: dict, files2: dict,
                             top_file: str = None):
        """
        创建二聚体拓扑文件（使用 #include 方式）
        
        Args:
            mol1_name: 分子1的名称
            mol2_name: 分子2的名称
            files1: 分子1的文件字典
            files2: 分子2的文件字典
            top_file: 输出的 top 文件路径
            
        Returns:
            top_file: 生成的拓扑文件路径
        """
        if top_file is None:
            top_file = str(self.work_dir / f'{mol1_name}_{mol2_name}_dimer.top')
        
        with open(top_file, 'w') as f:
            f.write("; GROMACS topology file for dimer system\n")
            f.write("; Generated by DimerEnergyScannerFromParams\n")
            f.write(f"; Molecules: {mol1_name} + {mol2_name}\n\n")
            
            # Defaults section
            f.write("[ defaults ]\n")
            f.write("; nbfunc        comb-rule       gen-pairs       fudgeLJ     fudgeQQ\n")
            f.write("1               3               yes             0.5         0.5\n\n")
            
            # Atomtypes section
            f.write("[ atomtypes ]\n")
            f.write("; include atp/itp files here\n\n")
            
            # Include .atp files (atomtypes definitions)
            for mol_name, file_dict in [(mol1_name, files1), (mol2_name, files2)]:
                if file_dict['atp']:
                    atp_path = Path(file_dict['atp']).absolute()
                    f.write(f'#include "{atp_path}"\n')
            
            f.write("\n")
            
            # Include .itp files (molecule definitions)
            for mol_name, file_dict in [(mol1_name, files1), (mol2_name, files2)]:
                itp_path = Path(file_dict['itp']).absolute()
                f.write(f'#include "{itp_path}"\n')
            
            f.write("\n")
            
            # System section
            f.write("[ system ]\n")
            f.write("; Name\n")
            f.write(f"{mol1_name} {mol2_name} dimer\n\n")
            
            # Molecules section
            f.write("[ molecules ]\n")
            f.write("; Compound        #mols\n")
            f.write(f"{mol1_name}  1\n")
            f.write(f"{mol2_name}  1\n")
        
        print(f"✓ 二聚体拓扑文件已创建: {top_file}")
        
        return top_file
    
    def load_params_from_files(self, mol1_name: str, mol2_name: str,
                              mol1_params_json: str, mol2_params_json: str,
                              metadata_json: str = None):
        """
        从 JSON 文件加载力场参数
        
        Args:
            mol1_name: 分子1的名称
            mol2_name: 分子2的名称
            mol1_params_json: 分子1的参数文件路径
            mol2_params_json: 分子2的参数文件路径
            metadata_json: 元数据文件路径（可选）
            
        Returns:
            nonbonded_params: 完整的非键参数字典
        """
        # 加载分子1的参数
        with open(mol1_params_json, 'r') as f:
            params1 = json.load(f)
        
        # 加载分子2的参数
        with open(mol2_params_json, 'r') as f:
            params2 = json.load(f)
        
        # 加载或创建 metadata
        if metadata_json and os.path.exists(metadata_json):
            with open(metadata_json, 'r') as f:
                metadata_dict = json.load(f)
                metadata = metadata_dict.get('metadata', metadata_dict)
        else:
            # 使用默认 metadata
            metadata = {
                's12': 0.15,
                'disp_damping': 0.4
            }
            print("  使用默认 metadata 参数")
        
        # 构建完整的非键参数字典
        nonbonded_params = {
            'metadata': metadata,
            mol1_name: params1,
            mol2_name: params2
        }
        
        # 保存完整参数供参考
        full_params_file = self.work_dir / f'{mol1_name}_{mol2_name}_nonbonded_params.json'
        with open(full_params_file, 'w') as f:
            json.dump(nonbonded_params, f, indent=2)
        print(f"✓ 完整非键参数已保存到: {full_params_file}")
        
        return nonbonded_params
    
    def load_geometries(self, mol1_gro: str, mol2_gro: str):
        """
        从 gro 文件加载分子几何结构
        
        Args:
            mol1_gro: 分子1的 gro 文件路径
            mol2_gro: 分子2的 gro 文件路径
            
        Returns:
            coords1, coords2: 两个分子的坐标 (numpy arrays)
        """
        import ase.io as aio
        
        atoms1 = aio.read(mol1_gro)
        atoms2 = aio.read(mol2_gro)
        
        coords1 = atoms1.get_positions()  # Å
        coords2 = atoms2.get_positions()  # Å
        
        return coords1, coords2
    
    def load_dimer_structures_from_dir(self, structure_dir: str, mol1_name: str, mol2_name: str):
        """
        从目录加载二聚体结构（每个 xyz 文件包含多个构象）
        文件格式: {dirname}/{name}_0.xyz 和 {dirname}/{name}_1.xyz
        每个 xyz 文件包含多帧结构
        
        Args:
            structure_dir: 包含子目录的根目录
            mol1_name: 分子1的名称
            mol2_name: 分子2的名称
            
        Returns:
            coords_list: 坐标列表
            distances: 距离列表
            dir_names: 目录名列表
        """
        from bytemol.core import Molecule
        
        structure_dir = Path(structure_dir)
        if not structure_dir.exists():
            raise ValueError(f"结构目录不存在: {structure_dir}")
        
        # 获取所有子目录
        subdirs = [d for d in structure_dir.iterdir() if d.is_dir()]
        
        if not subdirs:
            raise ValueError(f"在 {structure_dir} 中未找到子目录")
        
        print(f"找到 {len(subdirs)} 个子目录")
        
        coords_list = []
        distances = []
        dir_names = []
        conformer_ids = []  # 记录每个构象所属的目录和帧号
        
        for subdir in sorted(subdirs):
            dirname = subdir.name
            
            # 查找 xyz 文件: {name}_0.xyz 和 {name}_1.xyz
            xyz_files = []
            for i, name in enumerate([mol1_name, mol2_name]):
                xyz_file = subdir / f'{name}_{i}.xyz'
                if not xyz_file.exists():
                    print(f"  警告: 未找到 {xyz_file}，跳过 {dirname}")
                    break
                xyz_files.append(str(xyz_file))
            
            if len(xyz_files) != 2:
                continue
            
            try:
                # 使用 bytemol.Molecule 加载（支持多构象）
                mols = [Molecule(xyz_file) for xyz_file in xyz_files]
                
                # 获取构象数
                nconfs1 = mols[0].nconfs
                nconfs2 = mols[1].nconfs
                
                if nconfs1 != nconfs2:
                    print(f"  警告: {dirname} 中两个分子的构象数不匹配 ({nconfs1} vs {nconfs2})，跳过")
                    continue
                
                print(f"  处理 {dirname}: {nconfs1} 个构象")
                
                # 遍历每个构象
                for conf_idx in range(nconfs1):
                    # 获取坐标 (通过 get_confdata 获取所有构象的坐标)
                    coords_raw = [np.array(mol.get_confdata('coords')) for mol in mols]
                    
                    # coords_raw 的形状是 (nconfs, natoms, 3)
                    # 提取第 conf_idx 个构象
                    coords1 = coords_raw[0][conf_idx]
                    coords2 = coords_raw[1][conf_idx]
                    
                    # 合并坐标
                    coords = np.vstack([coords1, coords2])
                    coords_list.append(coords)
                    
                    # 计算质心距离
                    center1 = coords1.mean(axis=0)
                    center2 = coords2.mean(axis=0)
                    distance = np.linalg.norm(center2 - center1)
                    distances.append(distance)
                    
                    # 记录信息
                    dir_names.append(dirname)
                    conformer_ids.append((dirname, conf_idx))
                    
                    if conf_idx < 3 or conf_idx == nconfs1 - 1:  # 只打印前3个和最后一个
                        print(f"    构象 {conf_idx:3d}: d = {distance:.3f} Å")
                    elif conf_idx == 3:
                        print(f"    ...")
                
            except Exception as e:
                print(f"  ✗ 加载 {dirname} 时出错: {e}")
                import traceback
                traceback.print_exc()
                continue
        
        if not coords_list:
            raise ValueError("未能加载任何有效的结构")
        
        print(f"\n✓ 总共加载 {len(coords_list)} 个二聚体构象")
        
        # 按距离排序
        sorted_indices = np.argsort(distances)
        coords_list = [coords_list[i] for i in sorted_indices]
        distances = [distances[i] for i in sorted_indices]
        dir_names = [dir_names[i] for i in sorted_indices]
        conformer_ids = [conformer_ids[i] for i in sorted_indices]
        
        return coords_list, distances, dir_names, conformer_ids
    
    def generate_scan_geometries(self, coords1, coords2, 
                                  distances, scan_direction='x'):
        """
        生成不同距离的二聚体几何构型
        
        Args:
            coords1, coords2: 两个分子的坐标
            distances: 扫描距离数组 (Å)
            scan_direction: 扫描方向 ('x', 'y', 'z')
            
        Returns:
            coords_list: 每个距离对应的坐标数组列表
        """
        coords1 = coords1.copy()
        coords2 = coords2.copy()
        
        # 中心化分子
        center1 = coords1.mean(axis=0)
        center2 = coords2.mean(axis=0)
        coords1 -= center1
        coords2 -= center2
        
        # 设置扫描方向向量
        direction_map = {'x': [1, 0, 0], 'y': [0, 1, 0], 'z': [0, 0, 1]}
        direction = np.array(direction_map[scan_direction])
        
        coords_list = []
        for d in distances:
            # mol1 放在原点，mol2 沿扫描方向移动
            coords2_shifted = coords2 + direction * d
            combined_coords = np.vstack([coords1, coords2_shifted])
            coords_list.append(combined_coords)
        
        return coords_list
    
    def calculate_from_structure_dir(self,
                                     mol1_name: str,
                                     mol2_name: str,
                                     structure_dir: str,
                                     platform='CPU',
                                     compare_qm: bool = False):
        """
        从结构目录计算能量（支持多构象 xyz 文件）
        
        Args:
            mol1_name: 分子1的名称
            mol2_name: 分子2的名称
            structure_dir: 包含子目录的根目录，每个子目录包含 {name}_0.xyz 和 {name}_1.xyz
            platform: OpenMM 平台
            compare_qm: 是否尝试加载 QM 参考数据（EDA.json）
            
        Returns:
            results: 包含距离、能量和能量分解的字典
        """
        # 1. 查找参数文件
        print("\n" + "="*60)
        print("步骤 1: 查找分子文件")
        print("="*60)
        files1 = self.find_molecule_files(mol1_name)
        print()
        files2 = self.find_molecule_files(mol2_name)
        
        # 2. 加载结构（支持多构象）
        print("\n" + "="*60)
        print("步骤 2: 加载二聚体结构（多构象）")
        print("="*60)
        coords_list, distances, dir_names, conformer_ids = self.load_dimer_structures_from_dir(
            structure_dir, mol1_name, mol2_name
        )
        
        # 3. 创建二聚体拓扑文件
        print("\n" + "="*60)
        print("步骤 3: 创建二聚体拓扑")
        print("="*60)
        top_file = self.create_dimer_topology(
            mol1_name, mol2_name, files1, files2
        )
        
        # 4. 加载力场参数
        print("\n" + "="*60)
        print("步骤 4: 加载力场参数")
        print("="*60)
        
        metadata_json = files1['metadata'] or files2['metadata']
        
        nonbonded_params = self.load_params_from_files(
            mol1_name, mol2_name,
            files1['params'], files2['params'],
            metadata_json
        )
        
        # 5. 创建 OpenMM Calculator
        print("\n" + "="*60)
        print("步骤 5: 创建 OpenMM Calculator")
        print("="*60)
        
        try:
            calculator = AmoebaCalculator(
                top_file=top_file,
                nonbonded_params=nonbonded_params,
                platform_name=platform,
                separate_terms=True,
                unit_cell=None            )
            print(f"✓ Calculator 创建完成 (平台: {platform})")
        except Exception as e:
            print(f"✗ 创建 Calculator 时出错: {e}")
            raise
        
        # 6. 加载 QM 数据（如果需要）
        qm_data_dict = {}
        if compare_qm:
            print("\n" + "="*60)
            print("步骤 6: 加载 QM 参考数据")
            print("="*60)
            
            for dirname in set(dir_names):
                qm_file = Path(structure_dir) / dirname / 'EDA.json'
                if qm_file.exists():
                    try:
                        with open(qm_file, 'r') as f:
                            qm_data_dict[dirname] = json.load(f)
                        print(f"  ✓ 加载 {dirname}/EDA.json")
                    except Exception as e:
                        print(f"  ✗ 加载 {qm_file} 时出错: {e}")
        
        # 7. 计算能量
        print("\n" + "="*60)
        print("步骤 7: 计算能量")
        print("="*60)
        
        results = {
            'mol1_name': mol1_name,
            'mol2_name': mol2_name,
            'source': 'structure_dir',
            'structure_dir': str(structure_dir),
            'dir_names': dir_names,
            'conformer_ids': [(d, int(i)) for d, i in conformer_ids],
            'distances': [float(d) for d in distances],
            'total_energy': [],
            'energy_components': {},
        }
        
        # 如果需要比较 QM 数据
        if compare_qm and qm_data_dict:
            results['qm_data'] = {}
        
        for i, (d, coords, dirname, conf_id) in enumerate(zip(distances, coords_list, dir_names, conformer_ids)):
            print(f"  [{i+1:3d}/{len(coords_list)}] {dirname:25s} 构象 {conf_id[1]:3d}  d = {d:.2f} Å", 
                  end='', flush=True)
            
            # 计算总能量和力
            energy, forces = calculator._calculate_without_restraint(coords)
            results['total_energy'].append(energy)
            
            # 获取能量分解
            separate_energy, separate_forces = calculator.get_separate_terms()
            
            for term, e in separate_energy.items():
                if term not in results['energy_components']:
                    results['energy_components'][term] = []
                results['energy_components'][term].append(e)
            
            print(f"  →  E = {energy:10.4f} kcal/mol")
            
            # 添加 QM 数据
            if compare_qm and dirname in qm_data_dict:
                qm_data = qm_data_dict[dirname]
                
                if i == 0:
                    # 初始化 QM 数据键
                    for key in qm_data:
                        results['qm_data'][key] = []
                
                # 添加 QM 数据（对应当前构象）
                for key in results['qm_data']:
                    if key in qm_data:
                        val = qm_data[key]
                        # 如果是列表，取对应构象的值
                        if isinstance(val, list):
                            results['qm_data'][key].append(val[conf_id[1]] if conf_id[1] < len(val) else None)
                        else:
                            results['qm_data'][key].append(val)
                    else:
                        results['qm_data'][key].append(None)
        
        # 8. 保存结果
        results_file = self.work_dir / f'{mol1_name}_{mol2_name}_results.json'
        with open(results_file, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"\n✓ 结果已保存到: {results_file}")
        
        return results
    
    def calculate_dimer_scan(self, 
                            mol1_name: str, 
                            mol2_name: str,
                            distances=None,
                            scan_direction='x',
                            platform='CPU'):
        """
        执行完整的二聚体能量扫描（自动查找文件）
        
        Args:
            mol1_name: 分子1的名称（对应 params 下的文件夹名）
            mol2_name: 分子2的名称（对应 params 下的文件夹名）
            distances: 扫描距离数组 (Å)
            scan_direction: 扫描方向
            platform: OpenMM 平台 ('CPU' 或 'CUDA')
            
        Returns:
            results: 包含距离、能量和能量分解的字典
        """
        if distances is None:
            distances = np.linspace(2.5, 8.0, 20)
        
        # 1. 查找文件
        print("\n" + "="*60)
        print("步骤 1: 查找分子文件")
        print("="*60)
        files1 = self.find_molecule_files(mol1_name)
        print()
        files2 = self.find_molecule_files(mol2_name)
        
        # 2. 创建二聚体拓扑文件
        print("\n" + "="*60)
        print("步骤 2: 创建二聚体拓扑")
        print("="*60)
        top_file = self.create_dimer_topology(
            mol1_name, mol2_name, files1, files2
        )
        
        # 3. 加载力场参数
        print("\n" + "="*60)
        print("步骤 3: 加载力场参数")
        print("="*60)
        
        # 优先使用 mol1 的 metadata，如果没有则使用 mol2 的
        metadata_json = files1['metadata'] or files2['metadata']
        
        nonbonded_params = self.load_params_from_files(
            mol1_name, mol2_name,
            files1['params'], files2['params'],
            metadata_json
        )
        
        # 4. 加载分子几何结构
        print("\n" + "="*60)
        print("步骤 4: 加载分子几何结构")
        print("="*60)
        coords1, coords2 = self.load_geometries(files1['gro'], files2['gro'])
        print(f"  {mol1_name} 原子数: {len(coords1)}")
        print(f"  {mol2_name} 原子数: {len(coords2)}")
        
        # 5. 创建 OpenMM Calculator
        print("\n" + "="*60)
        print("步骤 5: 创建 OpenMM Calculator")
        print("="*60)
        
        try:
            calculator = AmoebaCalculator(
                top_file=top_file,
                nonbonded_params=nonbonded_params,
                platform_name=platform,
                separate_terms=True  # 开启能量分解
            )
            print(f"✓ Calculator 创建完成 (平台: {platform})")
        except Exception as e:
            print(f"✗ 创建 Calculator 时出错: {e}")
            print("\n调试信息 - 拓扑文件内容:")
            with open(top_file, 'r') as f:
                for i, line in enumerate(f, 1):
                    print(f"{i:3d}: {line.rstrip()}")
            raise
        
        # 6. 生成扫描几何构型
        print("\n" + "="*60)
        print("步骤 6: 生成扫描构型")
        print("="*60)
        coords_list = self.generate_scan_geometries(
            coords1, coords2, distances, scan_direction
        )
        print(f"  生成 {len(distances)} 个构型")
        print(f"  距离范围: {distances[0]:.2f} - {distances[-1]:.2f} Å")
        print(f"  扫描方向: {scan_direction}")
        
        # 7. 计算能量
        print("\n" + "="*60)
        print("步骤 7: 计算能量")
        print("="*60)
        
        results = {
            'mol1_name': mol1_name,
            'mol2_name': mol2_name,
            'scan_direction': scan_direction,
            'source': 'scan',
            'distances': distances.tolist(),
            'total_energy': [],
            'energy_components': {},
        }
        
        for i, (d, coords) in enumerate(zip(distances, coords_list)):
            print(f"  [{i+1:2d}/{len(distances)}] d = {d:.2f} Å", end='', flush=True)
            
            # 计算总能量和力
            energy, forces = calculator._calculate_without_restraint(coords)
            results['total_energy'].append(energy)
            
            # 获取能量分解
            separate_energy, separate_forces = calculator.get_separate_terms()
            
            for term, e in separate_energy.items():
                if term not in results['energy_components']:
                    results['energy_components'][term] = []
                results['energy_components'][term].append(e)
            
            print(f"  →  E = {energy:10.4f} kcal/mol")
        
        # 8. 保存结果
        results_file = self.work_dir / f'{mol1_name}_{mol2_name}_scan_results.json'
        with open(results_file, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"\n✓ 结果已保存到: {results_file}")
        
        return results
    
    def plot_energy_decomposition(self, results, save_path=None, 
                                  components_to_plot=None,
                                  plot_qm=False,
                                  figsize=(14, 9)):
        """
        绘制能量分解图
        
        Args:
            results: 结果字典
            save_path: 保存路径
            components_to_plot: 要绘制的分量
            plot_qm: 是否绘制 QM 参考数据
            figsize: 图片大小
        """
        distances = np.array(results['distances'])
        total_energy = np.array(results['total_energy'])
        print(total_energy)
        components = results['energy_components']
        total_energy = np.array(results['energy_components']['AmoebaMultipoleForce'])+ np.array(results['energy_components']['CustomNonbondedForce'])
        print(total_energy)
        # 如果未指定，默认绘制主要分量
        if components_to_plot is None:
            component_priority = [
                'AmoebaMultipoleForce',
                'CustomNonbondedForce', 
                # 'CustomBondForce',
                # 'HarmonicBondForce',
                # 'HarmonicAngleForce',
                # 'PeriodicTorsionForce'
            ]
            components_to_plot = [c for c in component_priority if c in components]
            
            if not components_to_plot:
                components_to_plot = list(components.keys())
        
        # 创建图形
        fig = plt.figure(figsize=figsize)
        gs = fig.add_gridspec(2, 2, height_ratios=[2, 1], width_ratios=[3, 1])
        
        ax1 = fig.add_subplot(gs[0, :])  # 上面整行
        ax2 = fig.add_subplot(gs[1, 0])  # 左下
        ax3 = fig.add_subplot(gs[1, 1])  # 右下
        
        # 定义颜色方案
        colors = plt.cm.tab10(np.linspace(0, 1, len(components_to_plot) + 1))
        
        mol1_name = results.get('mol1_name', 'MOL1')
        mol2_name = results.get('mol2_name', 'MOL2')
        source = results.get('source', 'unknown')
        
        # 上图: 总能量和各分量
        ax1.plot(distances, total_energy, 'k-', linewidth=3, 
                label='FF Total', marker='o', markersize=6, zorder=10)
        
        # 如果有 QM 数据，绘制参考线
        if plot_qm and 'qm_data' in results and 'TOTAL' in results['qm_data']:
            qm_total = np.array(results['qm_data']['TOTAL'])
            # 过滤掉 None 值
            valid_mask = np.array([v is not None for v in qm_total])
            if valid_mask.any():
                qm_total_valid = np.array([v if v is not None else np.nan for v in qm_total])
                ax1.plot(distances, qm_total_valid, 'r--', linewidth=2.5, 
                        label='QM Total', marker='^', markersize=5, alpha=0.8)
        
        for i, component in enumerate(components_to_plot):
            if component in components:
                energy = np.array(components[component])
                label = component.replace('Force', '').replace('Amoeba', '').replace('Custom', '')
                ax1.plot(distances, energy, '-', linewidth=2.5, 
                        label=label, color=colors[i], 
                        marker='s', markersize=4, alpha=0.85)
        
        ax1.set_xlabel('Distance (Å)', fontsize=13, fontweight='bold')
        ax1.set_ylabel('Energy (kcal/mol)', fontsize=13, fontweight='bold')
        
        title = f'{mol1_name}···{mol2_name} Dimer Interaction Energy'
        if source == 'structure_dir':
            title += f' ({len(distances)} conformers)'
        ax1.set_title(title, fontsize=15, fontweight='bold', pad=15)
        
        ax1.legend(loc='best', fontsize=10, framealpha=0.95, ncol=3)
        ax1.grid(True, alpha=0.3, linestyle='--')
        ax1.axhline(y=0, color='gray', linestyle='--', linewidth=1.5, alpha=0.6)
        
        # 左下图: 堆叠图
        component_arrays = []
        labels = []
        for component in components_to_plot:
            if component in components:
                component_arrays.append(np.array(components[component]))
                label = component.replace('Force', '').replace('Amoeba', '').replace('Custom', '')
                labels.append(label)
        
        if component_arrays:
            ax2.stackplot(distances, *component_arrays, 
                         labels=labels, alpha=0.75, colors=colors[:len(labels)])
            ax2.set_xlabel('Distance (Å)', fontsize=11, fontweight='bold')
            ax2.set_ylabel('Energy (kcal/mol)', fontsize=11, fontweight='bold')
            ax2.set_title('Stacked Components', fontsize=12, fontweight='bold')
            ax2.legend(loc='upper right', fontsize=8, framealpha=0.9)
            ax2.grid(True, alpha=0.3, linestyle='--')
        
        # 右下图: 能量分量占比（饼图）
        avg_contributions = {}
        for component in components_to_plot:
            if component in components:
                energy = np.abs(np.array(components[component]))
                avg_contributions[component] = np.mean(energy)
        
        if avg_contributions:
            labels_pie = [c.replace('Force', '').replace('Amoeba', '').replace('Custom', '') 
                         for c in avg_contributions.keys()]
            sizes = list(avg_contributions.values())
            
            ax3.pie(sizes, labels=labels_pie, autopct='%1.1f%%',
                   colors=colors[:len(labels_pie)], startangle=90)
            ax3.set_title('Average Contribution', fontsize=12, fontweight='bold')
        
        plt.tight_layout()
        
        # 保存图片
        if save_path is None:
            suffix = '_structures' if source == 'structure_dir' else ''
            save_path = self.work_dir / f'{mol1_name}_{mol2_name}_energy_decomposition{suffix}.png'
        
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✓ 能量分解图已保存到: {save_path}")
        
        # 同时保存 PDF 版本
        pdf_path = Path(save_path).with_suffix('.pdf')
        plt.savefig(pdf_path, bbox_inches='tight')
        print(f"✓ PDF 版本已保存到: {pdf_path}")
        
        plt.show()
        
        return fig, (ax1, ax2, ax3)
    
    def analyze_interaction_energy(self, results):
        """
        分析相互作用能
        """
        distances = np.array(results['distances'])
        energies = np.array(results['total_energy'])
        
        # 找到能量最小值
        min_idx = np.argmin(energies)
        min_distance = distances[min_idx]
        min_energy = energies[min_idx]
        
        # 估算平衡距离（能量为零的点）
        zero_crossings = []
        for i in range(len(energies) - 1):
            if energies[i] * energies[i+1] < 0:
                d0 = distances[i] + (distances[i+1] - distances[i]) * \
                     (-energies[i]) / (energies[i+1] - energies[i])
                zero_crossings.append(d0)
        
        # 找最大值（排斥最强点）
        max_idx = np.argmax(energies)
        max_distance = distances[max_idx]
        max_energy = energies[max_idx]
        
        analysis = {
            'equilibrium_distance': float(min_distance),
            'minimum_energy': float(min_energy),
            'maximum_distance': float(max_distance),
            'maximum_energy': float(max_energy),
            'zero_crossing_distances': [float(d) for d in zero_crossings],
            'attractive_range': (float(distances[energies < 0].min()) if any(energies < 0) else None,
                               float(distances[energies < 0].max()) if any(energies < 0) else None),
            'energy_range': (float(energies.min()), float(energies.max()))
        }
        
        mol1 = results.get('mol1_name', 'MOL1')
        mol2 = results.get('mol2_name', 'MOL2')
        
        print("\n" + "="*60)
        print(f"{mol1}···{mol2} 相互作用能分析")
        print("="*60)
        print(f"能量最小值:     {min_energy:10.4f} kcal/mol  @  {min_distance:.3f} Å")
        print(f"能量最大值:     {max_energy:10.4f} kcal/mol  @  {max_distance:.3f} Å")
        print(f"能量范围:       {analysis['energy_range'][0]:10.4f} ~ {analysis['energy_range'][1]:10.4f} kcal/mol")
        
        if zero_crossings:
            print(f"能量零点:       {', '.join([f'{d:.3f}' for d in zero_crossings])} Å")
        
        if analysis['attractive_range'][0] is not None:
            print(f"吸引力区域:     {analysis['attractive_range'][0]:.3f} - {analysis['attractive_range'][1]:.3f} Å")
        
        # 保存分析结果
        source = results.get('source', 'scan')
        suffix = '_structures' if source == 'structure_dir' else ''
        analysis_file = self.work_dir / f"{mol1}_{mol2}_analysis{suffix}.json"
        with open(analysis_file, 'w') as f:
            json.dump(analysis, f, indent=2)
        print(f"\n✓ 分析结果已保存到: {analysis_file}")
        
        return analysis


def main():
    """
    主函数：Li-EC 示例
    """
    import argparse
    
    parser = argparse.ArgumentParser(
        description='从 params 文件夹进行二聚体能量计算',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # Li-EC 二聚体扫描（自动生成构型）
  python dimer_scan_from_params_folder_final.py --mol1 LI --mol2 EC
  
  # 从结构目录计算（每个子目录包含多构象 {name}_0.xyz 和 {name}_1.xyz）
  python dimer_scan_from_params_folder_final.py --mol1 LI --mol2 EC --structure_dir ./dimer_structures
  
  # 从结构目录计算并比较 QM 数据（需要 EDA.json 文件）
  python dimer_scan_from_params_folder_final.py --mol1 LI --mol2 EC --structure_dir ./dimer_structures --compare_qm
  
  # 自定义距离范围
  python dimer_scan_from_params_folder_final.py --mol1 LI --mol2 EC --dmin 1.5 --dmax 6.0 --npoints 30
  
  # 使用 GPU
  python dimer_scan_from_params_folder_final.py --mol1 LI --mol2 EC --platform CUDA
        """
    )
    
    parser.add_argument('--mol1', type=str, default='LI',
                       help='分子1的名称（params 文件夹下的子目录）')
    parser.add_argument('--mol2', type=str, default='EC',
                       help='分子2的名称（params 文件夹下的子目录）')
    parser.add_argument('--params_dir', type=str, default='./params',
                       help='参数文件夹根目录')
    parser.add_argument('--structure_dir', type=str, default=None,
                       help='结构目录（每个子目录包含多构象 {name}_0.xyz 和 {name}_1.xyz）')
    parser.add_argument('--compare_qm', action='store_true',
                       help='比较 QM 数据（需要结构目录中有 EDA.json 文件）')
    parser.add_argument('--dmin', type=float, default=1.5,
                       help='最小扫描距离 (Å) [仅用于自动生成构型]')
    parser.add_argument('--dmax', type=float, default=8.0,
                       help='最大扫描距离 (Å) [仅用于自动生成构型]')
    parser.add_argument('--npoints', type=int, default=25,
                       help='扫描点数 [仅用于自动生成构型]')
    parser.add_argument('--direction', type=str, default='x',
                       choices=['x', 'y', 'z'],
                       help='扫描方向 [仅用于自动生成构型]')
    parser.add_argument('--platform', type=str, default='CPU',
                       choices=['CPU', 'CUDA'],
                       help='OpenMM 计算平台')
    parser.add_argument('--work_dir', type=str, default=None,
                       help='工作目录（默认为 ./dimer_{mol1}_{mol2}）')
    
    args = parser.parse_args()
    
    # 设置工作目录
    if args.work_dir is None:
        args.work_dir = f'./dimer_{args.mol1}_{args.mol2}'
    
    print("="*60)
    print(f"🔬 二聚体能量计算: {args.mol1}···{args.mol2}")
    print("="*60)
    
    # 创建扫描器
    scanner = DimerEnergyScannerFromParams(
        params_dir=args.params_dir,
        work_dir=args.work_dir
    )
    
    # 判断是从结构目录还是自动生成构型
    if args.structure_dir:
        # 从结构目录计算（支持多构象）
        print(f"模式: 从结构目录读取多构象 ({args.structure_dir})")
        results = scanner.calculate_from_structure_dir(
            mol1_name=args.mol1,
            mol2_name=args.mol2,
            structure_dir=args.structure_dir,
            platform=args.platform,
            compare_qm=args.compare_qm
        )
        plot_qm = args.compare_qm
    else:
        # 自动生成扫描构型
        print(f"模式: 自动生成扫描构型")
        distances = np.linspace(args.dmin, args.dmax, args.npoints)
        results = scanner.calculate_dimer_scan(
            mol1_name=args.mol1,
            mol2_name=args.mol2,
            distances=distances,
            scan_direction=args.direction,
            platform=args.platform
        )
        plot_qm = False
    
    # 分析结果
    analysis = scanner.analyze_interaction_energy(results)
    
    # 绘制能量分解图
    scanner.plot_energy_decomposition(results, plot_qm=plot_qm)
    
    print("\n" + "="*60)
    print("✅ 计算完成！")
    print(f"📁 所有结果已保存到: {args.work_dir}")
    print("="*60)


if __name__ == '__main__':
    main()
