import os
import json
import argparse
import openmm as omm
import openmm.app as app
from byteff2.toolkit.protocol import Protocol
from byteff2.toolkit.openmmtool import generate_openmm_system

def generate_xml_pdb_from_smiles(smiles, mol_name, output_dir):
    """
    Generate OpenMM XML (serialized system) and PDB file from a SMILES string.
    """
    params_dir = os.path.join(output_dir, "params")
    working_dir = os.path.join(output_dir, "working")
    os.makedirs(params_dir, exist_ok=True)
    os.makedirs(working_dir, exist_ok=True)

    # 1. Initialize Protocol
    # Protocol takes params_dir (where to store generated parameters) 
    # and output_dir (not used much in generate_ff_params/build_system)
    proto = Protocol(params_dir=params_dir, output_dir=output_dir)

    # 2. Generate force field parameters (.itp, .atp, .gro, .json)
    print(f"Generating parameters for {mol_name} ({smiles})...")
    component_smiles = {mol_name: smiles}
    nonbonded_params = proto.generate_ff_params(component_smiles)

    # 3. Build a single-molecule gas-phase system to get the topology
    # total_atoms is just a hint, build_gas=True will handle single molecule
    print(f"Building gas-phase system for {mol_name}...")
    components_ratio = {mol_name: 1}
    proto.build_system(total_atoms=1, components_ratio=components_ratio, 
                       working_dir=working_dir, build_gas=True)

    # Files generated by build_system(build_gas=True) are in params_dir
    # actually build_system copies them to params_dir with specific names
    # solvent_salt_gas.gro and system_gas.top
    gro_file = os.path.join(params_dir, "solvent_salt_gas.gro")
    top_file = os.path.join(params_dir, "system_gas.top")

    # 4. Generate OpenMM System
    print("Generating OpenMM System...")
    top, system = generate_openmm_system(
        top_file=top_file,
        nonbonded_params=nonbonded_params,
        unit_cell=None # Gas phase, no periodic box
    )

    # 5. Serialize System to XML
    xml_path = os.path.join(output_dir, f"{mol_name}.xml")
    print(f"Saving serialized system to {xml_path}...")
    with open(xml_path, 'w') as f:
        f.write(omm.XmlSerializer.serialize(system))

    # 6. Save structure to PDB
    # We can get positions from the Molecule object created in generate_ff_params or from .gro
    # generate_ff_params returns the mol object as the 4th value if we look at protocol.py
    # but here we'll just re-read the molecule or use ASE if needed.
    # Actually, let's just use the Molecule object directly from the same logic as Protocol.
    from bytemol.core import Molecule
    mol = Molecule.from_smiles(smiles, nconfs=1)
    positions = mol.conformers[0].coords # in Angstrom
    
    pdb_path = os.path.join(output_dir, f"{mol_name}.pdb")
    print(f"Saving structure to {pdb_path}...")
    with open(pdb_path, 'w') as f:
        # OpenMM positions are in nm
        app.PDBFile.writeFile(top.topology, positions / 10 * omm.unit.nanometers, f)

    print("Done!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate OpenMM XML and PDB from SMILES")
    parser.add_argument("--smiles", type=str, required=True, help="SMILES string of the molecule")
    parser.add_argument("--name", type=str, default="molecule", help="Name of the molecule")
    parser.add_argument("--output", type=str, default="output", help="Output directory")

    args = parser.parse_args()

    generate_xml_pdb_from_smiles(args.smiles, args.name, args.output)
